apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ovnk-observ-exporter
  namespace: ovnk-observ
spec:
  # Lets pods in this namespace use the short name ovnk-observ-exporter:latest.
  lookupPolicy:
    local: true
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: ovnk-observ-exporter
  namespace: ovnk-observ
spec:
  runPolicy: Serial
  source:
    type: Binary
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile
  output:
    to:
      kind: ImageStreamTag
      name: ovnk-observ-exporter:latest
