PROMETHEUS_VERSION ?= 3.5.0
HOST_OS := $(shell go env GOOS)
HOST_ARCH := $(shell go env GOARCH)

NODE ?= <worker-node>

IMG ?= quay.io/cragr/ovnk-observ-exporter
VERSION ?= v0.1.0

.PHONY: build test tools image-build image-push image-dev deploy undeploy verify-counts integration rules-test rules-gen dashboard dashboard-apply verify-panels

build:
	CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bin/ovnk-observ-exporter ./cmd/ovnk-observ-exporter

test:
	go test ./...

tools: bin/promtool

bin/promtool:
	mkdir -p bin
	curl -fsSL https://github.com/prometheus/prometheus/releases/download/v$(PROMETHEUS_VERSION)/prometheus-$(PROMETHEUS_VERSION).$(HOST_OS)-$(HOST_ARCH).tar.gz \
		| tar -xz -C bin --strip-components=1 prometheus-$(PROMETHEUS_VERSION).$(HOST_OS)-$(HOST_ARCH)/promtool

# Release image. .containerignore limits the context to the Containerfile and binary.
image-build: build
	podman build --platform linux/amd64 -f Containerfile --build-arg VERSION=$(VERSION) \
		-t $(IMG):$(VERSION) -t $(IMG):latest .

image-push:
	podman push $(IMG):$(VERSION)
	podman push $(IMG):latest

# Dev image: in-cluster BuildConfig build. Upload only the Containerfile and
# binary, not the whole repo (bin/promtool is ~150MB).
image-dev: build
	@ctx=$$(mktemp -d) && trap 'rm -rf "$$ctx"' EXIT && \
		mkdir -p "$$ctx/bin" && cp Containerfile "$$ctx/" && cp bin/ovnk-observ-exporter "$$ctx/bin/" && \
		oc start-build ovnk-observ-exporter -n ovnk-observ --from-dir="$$ctx" --follow

deploy:
	oc apply -k deploy/

undeploy:
	oc delete -f deploy/dashboard-configmap.yaml --ignore-not-found
	oc delete -k deploy/ --ignore-not-found

verify-counts:
	hack/verify-counts.sh $(NODE)

integration:
	hack/integration/run.sh

rules-test: bin/promtool
	bin/promtool check rules rules/ovnk-observ-rules.yaml
	bin/promtool test rules rules/tests/rules_test.yaml

# Wrap the rule groups into the PrometheusRule applied by deploy/.
rules-gen:
	@{ \
	  echo "# Generated by 'make rules-gen' from rules/ovnk-observ-rules.yaml. Do not edit."; \
	  echo "apiVersion: monitoring.coreos.com/v1"; \
	  echo "kind: PrometheusRule"; \
	  echo "metadata:"; \
	  echo "  name: ovnk-observ"; \
	  echo "  namespace: ovnk-observ"; \
	  echo "  labels:"; \
	  echo "    role: alert-rules"; \
	  echo "spec:"; \
	  sed 's/^/  /' rules/ovnk-observ-rules.yaml; \
	} > deploy/prometheusrule.yaml

# The dashboard ConfigMap lives in openshift-config-managed, outside the kustomize tree.
dashboard:
	go run ./hack/dashgen -out dashboards/ -configmap deploy/dashboard-configmap.yaml

dashboard-apply:
	oc apply -f deploy/dashboard-configmap.yaml

verify-panels:
	hack/verify-panels.sh
