PROMETHEUS_VERSION ?= 3.5.0
# The install manifest is rendered with this kustomize release (make tools).
KUSTOMIZE_VERSION ?= v5.8.1
HOST_OS := $(shell go env GOOS)
HOST_ARCH := $(shell go env GOARCH)

IMG ?= quay.io/cragr/ovnk-observ-exporter
VERSION ?= v0.1.0
KUSTOMIZE := bin/kustomize-$(KUSTOMIZE_VERSION)
INSTALL_MANIFEST := install/ovnk-observ.yaml

.PHONY: build test tools image-build image-push image-dev deploy deploy-release undeploy set-version install-manifest render-install verify-install-manifest verify-counts integration rules-test rules-gen dashboard dashboard-apply verify-panels

build:
	CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bin/ovnk-observ-exporter ./cmd/ovnk-observ-exporter

test:
	go test ./...

tools: bin/promtool $(KUSTOMIZE)

$(KUSTOMIZE):
	mkdir -p bin
	curl -fsSL https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2F$(KUSTOMIZE_VERSION)/kustomize_$(KUSTOMIZE_VERSION)_$(HOST_OS)_$(HOST_ARCH).tar.gz \
		| tar -xz -C bin kustomize
	mv bin/kustomize $@

bin/promtool:
	mkdir -p bin
	curl -fsSL https://github.com/prometheus/prometheus/releases/download/v$(PROMETHEUS_VERSION)/prometheus-$(PROMETHEUS_VERSION).$(HOST_OS)-$(HOST_ARCH).tar.gz \
		| tar -xz -C bin --strip-components=1 prometheus-$(PROMETHEUS_VERSION).$(HOST_OS)-$(HOST_ARCH)/promtool

# Release image. .containerignore limits the context to the Containerfile and binary.
image-build: build
	podman build --platform linux/amd64 -f Containerfile --build-arg VERSION=$(VERSION) \
		-t $(IMG):$(VERSION) -t $(IMG):latest .

image-push:
	podman push $(IMG):$(VERSION)
	podman push $(IMG):latest

# Dev image: in-cluster BuildConfig build. Upload only the Containerfile and
# binary, not the whole repo (bin/promtool is ~150MB).
image-dev: build
	@ctx=$$(mktemp -d) && trap 'rm -rf "$$ctx"' EXIT && \
		mkdir -p "$$ctx/bin" && cp Containerfile "$$ctx/" && cp bin/ovnk-observ-exporter "$$ctx/bin/" && \
		oc start-build ovnk-observ-exporter -n ovnk-observ --from-dir="$$ctx" --follow
	@# Admission stores the resolved digest in the pod templates, so a restart or
	@# re-apply keeps the old build. Setting the short name again makes admission
	@# resolve it to the new digest, which rolls the pods.
	oc set image ds/ovnk-observ-node deploy/ovnk-observ-cluster exporter=ovnk-observ-exporter:latest -n ovnk-observ

# Dev: deploy/ plus the in-cluster BuildConfig (overlays/dev). Run make image-dev next.
deploy:
	oc apply -k overlays/dev/

# Release: the rendered install manifest, as an admin would apply it.
deploy-release:
	oc apply -f $(INSTALL_MANIFEST)

undeploy:
	oc delete -f deploy/dashboard-configmap.yaml --ignore-not-found
	oc delete -k overlays/dev/ --ignore-not-found

# Set the release image tag in deploy/kustomization.yaml (the only place it lives).
set-version: $(KUSTOMIZE)
	cd deploy && ../$(KUSTOMIZE) edit set image $(IMG):$(VERSION)

# One file for admins: deploy/ (namespace and PriorityClass first, PrometheusRule
# included) followed by the dashboard ConfigMap in openshift-config-managed.
install-manifest: set-version
	@$(MAKE) --no-print-directory render-install

render-install: $(KUSTOMIZE)
	@mkdir -p $(dir $(INSTALL_MANIFEST))
	@{ \
	  echo "# Generated by 'make install-manifest' from deploy/. Do not edit."; \
	  echo "# Install: oc apply -f ovnk-observ.yaml   Uninstall: oc delete -f ovnk-observ.yaml"; \
	  $(KUSTOMIZE) build deploy/; \
	  echo "---"; \
	  cat deploy/dashboard-configmap.yaml; \
	} > $(INSTALL_MANIFEST)

# Fails if the committed install manifest is stale, or if the DaemonSet and the
# Deployment do not both run $(IMG):$(VERSION). Changes no tracked file.
verify-install-manifest: $(KUSTOMIZE)
	@tmp=$$(mktemp) && trap 'rm -f "$$tmp"' EXIT && \
		$(MAKE) --no-print-directory render-install INSTALL_MANIFEST=$$tmp && \
		diff -u $(INSTALL_MANIFEST) $$tmp || { echo "$(INSTALL_MANIFEST) is stale: run make install-manifest" >&2; exit 1; }
	@n=$$(grep -c 'image: $(IMG):$(VERSION)$$' $(INSTALL_MANIFEST)); [ "$$n" -eq 2 ] || \
		{ echo "$(INSTALL_MANIFEST): $$n of 2 workloads use $(IMG):$(VERSION); run make install-manifest" >&2; exit 1; }

verify-counts:
	@test -n "$(NODE)" || { echo "usage: make verify-counts NODE=<node-name>" >&2; exit 2; }
	hack/verify-counts.sh $(NODE)

integration:
	hack/integration/run.sh

rules-test: bin/promtool
	bin/promtool check rules rules/ovnk-observ-rules.yaml
	bin/promtool test rules rules/tests/rules_test.yaml

# Wrap the rule groups into the PrometheusRule applied by deploy/.
rules-gen:
	@{ \
	  echo "# Generated by 'make rules-gen' from rules/ovnk-observ-rules.yaml. Do not edit."; \
	  echo "apiVersion: monitoring.coreos.com/v1"; \
	  echo "kind: PrometheusRule"; \
	  echo "metadata:"; \
	  echo "  name: ovnk-observ"; \
	  echo "  namespace: ovnk-observ"; \
	  echo "  labels:"; \
	  echo "    role: alert-rules"; \
	  echo "spec:"; \
	  sed 's/^/  /' rules/ovnk-observ-rules.yaml; \
	} > deploy/prometheusrule.yaml

# The dashboard ConfigMap lives in openshift-config-managed, outside the kustomize tree.
dashboard:
	go run ./hack/dashgen -out dashboards/ -configmap deploy/dashboard-configmap.yaml

dashboard-apply:
	oc apply -f deploy/dashboard-configmap.yaml

verify-panels:
	hack/verify-panels.sh
