PROMETHEUS_VERSION ?= 3.5.0
HOST_OS := $(shell go env GOOS)
HOST_ARCH := $(shell go env GOARCH)

NODE ?= <worker-node>

IMG ?= quay.io/cragr/ovnk-observ-exporter
VERSION ?= v0.1.0
KUSTOMIZE ?= kustomize
INSTALL_MANIFEST := install/ovnk-observ.yaml

.PHONY: build test tools image-build image-push image-dev deploy deploy-release undeploy install-manifest verify-install-manifest verify-counts integration rules-test rules-gen dashboard dashboard-apply verify-panels

build:
	CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bin/ovnk-observ-exporter ./cmd/ovnk-observ-exporter

test:
	go test ./...

tools: bin/promtool

bin/promtool:
	mkdir -p bin
	curl -fsSL https://github.com/prometheus/prometheus/releases/download/v$(PROMETHEUS_VERSION)/prometheus-$(PROMETHEUS_VERSION).$(HOST_OS)-$(HOST_ARCH).tar.gz \
		| tar -xz -C bin --strip-components=1 prometheus-$(PROMETHEUS_VERSION).$(HOST_OS)-$(HOST_ARCH)/promtool

# Release image. .containerignore limits the context to the Containerfile and binary.
image-build: build
	podman build --platform linux/amd64 -f Containerfile --build-arg VERSION=$(VERSION) \
		-t $(IMG):$(VERSION) -t $(IMG):latest .

image-push:
	podman push $(IMG):$(VERSION)
	podman push $(IMG):latest

# Dev image: in-cluster BuildConfig build. Upload only the Containerfile and
# binary, not the whole repo (bin/promtool is ~150MB).
image-dev: build
	@ctx=$$(mktemp -d) && trap 'rm -rf "$$ctx"' EXIT && \
		mkdir -p "$$ctx/bin" && cp Containerfile "$$ctx/" && cp bin/ovnk-observ-exporter "$$ctx/bin/" && \
		oc start-build ovnk-observ-exporter -n ovnk-observ --from-dir="$$ctx" --follow
	oc rollout restart ds/ovnk-observ-node deploy/ovnk-observ-cluster -n ovnk-observ

# Dev: deploy/ plus the in-cluster BuildConfig (overlays/dev). Run make image-dev next.
deploy:
	oc apply -k overlays/dev/

# Release: the rendered install manifest, as an admin would apply it.
deploy-release:
	oc apply -f $(INSTALL_MANIFEST)

undeploy:
	oc delete -f deploy/dashboard-configmap.yaml --ignore-not-found
	oc delete -k overlays/dev/ --ignore-not-found

# One file for admins: deploy/ (namespace and PriorityClass first, PrometheusRule
# included) followed by the dashboard ConfigMap in openshift-config-managed.
install-manifest:
	@mkdir -p $(dir $(INSTALL_MANIFEST))
	@{ \
	  echo "# Generated by 'make install-manifest' from deploy/. Do not edit."; \
	  echo "# Install: oc apply -f ovnk-observ.yaml   Uninstall: oc delete -f ovnk-observ.yaml"; \
	  $(KUSTOMIZE) build deploy/; \
	  echo "---"; \
	  cat deploy/dashboard-configmap.yaml; \
	} > $(INSTALL_MANIFEST)

# Fails if the committed install manifest is stale or its image tag is not $(VERSION).
verify-install-manifest:
	@tmp=$$(mktemp) && trap 'rm -f "$$tmp"' EXIT && \
		$(MAKE) --no-print-directory install-manifest INSTALL_MANIFEST=$$tmp && \
		diff -u $(INSTALL_MANIFEST) $$tmp || { echo "$(INSTALL_MANIFEST) is stale: run make install-manifest" >&2; exit 1; }
	@grep -q 'image: $(IMG):$(VERSION)$$' $(INSTALL_MANIFEST) || \
		{ echo "$(INSTALL_MANIFEST) does not use $(IMG):$(VERSION)" >&2; exit 1; }

verify-counts:
	hack/verify-counts.sh $(NODE)

integration:
	hack/integration/run.sh

rules-test: bin/promtool
	bin/promtool check rules rules/ovnk-observ-rules.yaml
	bin/promtool test rules rules/tests/rules_test.yaml

# Wrap the rule groups into the PrometheusRule applied by deploy/.
rules-gen:
	@{ \
	  echo "# Generated by 'make rules-gen' from rules/ovnk-observ-rules.yaml. Do not edit."; \
	  echo "apiVersion: monitoring.coreos.com/v1"; \
	  echo "kind: PrometheusRule"; \
	  echo "metadata:"; \
	  echo "  name: ovnk-observ"; \
	  echo "  namespace: ovnk-observ"; \
	  echo "  labels:"; \
	  echo "    role: alert-rules"; \
	  echo "spec:"; \
	  sed 's/^/  /' rules/ovnk-observ-rules.yaml; \
	} > deploy/prometheusrule.yaml

# The dashboard ConfigMap lives in openshift-config-managed, outside the kustomize tree.
dashboard:
	go run ./hack/dashgen -out dashboards/ -configmap deploy/dashboard-configmap.yaml

dashboard-apply:
	oc apply -f deploy/dashboard-configmap.yaml

verify-panels:
	hack/verify-panels.sh
