apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac.yaml
  - build.yaml
  - node-daemonset.yaml
  - cluster-deployment.yaml
  - services.yaml
  - servicemonitors.yaml
