apiVersion: v1
kind: Namespace
metadata:
  name: ovnk-observ
  labels:
    openshift.io/cluster-monitoring: "true"
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
    security.openshift.io/scc.podSecurityLabelSync: "false"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: ovnk-observ
value: 1000000
preemptionPolicy: Never
description: OVN-Kubernetes observability exporter (below system-* classes).
