// Command dashgen generates the "Networking / OVN-K Observ" console
// dashboard JSON and the ConfigMap that installs it into
// openshift-config-managed.
//
//	go run ./hack/dashgen -out dashboards/ -configmap deploy/dashboard-configmap.yaml
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const (
	cmName    = "grafana-dashboard-ovn-scale-troubleshooting"
	cmNS      = "openshift-config-managed"
	cmDataKey = "ovn-scale-troubleshooting.json"
)

// DashboardJSON renders d as indented JSON without HTML escaping.
func DashboardJSON(d Dashboard) ([]byte, error) {
	var b bytes.Buffer
	enc := json.NewEncoder(&b)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")
	if err := enc.Encode(d); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

// ConfigMapYAML wraps the dashboard JSON in the ConfigMap the console watches.
func ConfigMapYAML(d Dashboard) ([]byte, error) {
	j, err := DashboardJSON(d)
	if err != nil {
		return nil, err
	}
	var b bytes.Buffer
	b.WriteString("# Generated by 'make dashboard' (hack/dashgen). Do not edit.\n")
	b.WriteString("apiVersion: v1\nkind: ConfigMap\nmetadata:\n")
	fmt.Fprintf(&b, "  name: %s\n  namespace: %s\n", cmName, cmNS)
	b.WriteString("  labels:\n    console.openshift.io/dashboard: \"true\"\n")
	fmt.Fprintf(&b, "data:\n  %s: |-\n", cmDataKey)
	for _, line := range strings.Split(strings.TrimRight(string(j), "\n"), "\n") {
		b.WriteString("    " + line + "\n")
	}
	return b.Bytes(), nil
}

func main() {
	out := flag.String("out", "dashboards/", "directory for the dashboard JSON")
	cm := flag.String("configmap", "deploy/dashboard-configmap.yaml", "path of the generated ConfigMap")
	flag.Parse()

	d := Build()
	j, err := DashboardJSON(d)
	if err == nil {
		err = os.WriteFile(filepath.Join(*out, cmDataKey), j, 0o644)
	}
	if err == nil {
		var y []byte
		if y, err = ConfigMapYAML(d); err == nil {
			err = os.WriteFile(*cm, y, 0o644)
		}
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "dashgen:", err)
		os.Exit(1)
	}
}
