// Command dashgen generates the "Networking / OVN-K Observ" console
// dashboard JSON and the ConfigMap that installs it into
// openshift-config-managed, plus the ACM hub fleet-triage dashboard and its
// ConfigMap for open-cluster-management-observability.
//
//	go run ./hack/dashgen -out dashboards/ -configmap deploy/dashboard-configmap.yaml -hub-configmap deploy/acm/dashboard-configmap.yaml [-acl-log-url URL [-acl-log-title TITLE]]
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const (
	cmName    = "grafana-dashboard-ovn-scale-troubleshooting"
	cmNS      = "openshift-config-managed"
	cmDataKey = "ovn-scale-troubleshooting.json"
)

// DashboardJSON renders d as indented JSON without HTML escaping.
func DashboardJSON(d Dashboard) ([]byte, error) { return encodeJSON(d) }

// HubJSON renders the hub dashboard like DashboardJSON.
func HubJSON(d HubDashboard) ([]byte, error) { return encodeJSON(d) }

func encodeJSON(d any) ([]byte, error) {
	var b bytes.Buffer
	enc := json.NewEncoder(&b)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")
	if err := enc.Encode(d); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

// ConfigMapYAML wraps the dashboard JSON in the ConfigMap the console watches.
func ConfigMapYAML(d Dashboard) ([]byte, error) {
	j, err := DashboardJSON(d)
	if err != nil {
		return nil, err
	}
	return wrapConfigMap(cmName, cmNS, `console.openshift.io/dashboard: "true"`, "", cmDataKey, j), nil
}

// HubConfigMapYAML wraps the hub dashboard JSON in the ConfigMap the ACM
// observability Grafana loads custom dashboards from.
func HubConfigMapYAML(d HubDashboard) ([]byte, error) {
	j, err := HubJSON(d)
	if err != nil {
		return nil, err
	}
	return wrapConfigMap(hubCMName, hubCMNS, `grafana-custom-dashboard: "true"`,
		"observability.open-cluster-management.io/dashboard-folder: "+hubFolder, hubDataKey, j), nil
}

// wrapConfigMap emits a ConfigMap with one label, an optional annotation, and
// j as a block scalar under key.
func wrapConfigMap(name, ns, label, annotation, key string, j []byte) []byte {
	var b bytes.Buffer
	b.WriteString("# Generated by 'make dashboard' (hack/dashgen). Do not edit.\n")
	b.WriteString("apiVersion: v1\nkind: ConfigMap\nmetadata:\n")
	fmt.Fprintf(&b, "  name: %s\n  namespace: %s\n", name, ns)
	fmt.Fprintf(&b, "  labels:\n    %s\n", label)
	if annotation != "" {
		fmt.Fprintf(&b, "  annotations:\n    %s\n", annotation)
	}
	fmt.Fprintf(&b, "data:\n  %s: |-\n", key)
	for _, line := range strings.Split(strings.TrimRight(string(j), "\n"), "\n") {
		b.WriteString("    " + line + "\n")
	}
	return b.Bytes()
}

func main() {
	out := flag.String("out", "dashboards/", "directory for the dashboard JSON")
	cm := flag.String("configmap", "deploy/dashboard-configmap.yaml", "path of the generated ConfigMap")
	hubCM := flag.String("hub-configmap", "deploy/acm/dashboard-configmap.yaml", "path of the generated ACM hub dashboard ConfigMap")
	aclURL := flag.String("acl-log-url", "", "optional URL of an external ACL allow/deny (or NetObserv drop) view, added as a dashboard link")
	aclTitle := flag.String("acl-log-title", DefaultACLLogTitle, "title of the -acl-log-url link")
	flag.Parse()

	d := Build(Options{ACLLogURL: *aclURL, ACLLogTitle: *aclTitle})
	j, err := DashboardJSON(d)
	if err == nil {
		err = os.WriteFile(filepath.Join(*out, cmDataKey), j, 0o644)
	}
	if err == nil {
		var y []byte
		if y, err = ConfigMapYAML(d); err == nil {
			err = os.WriteFile(*cm, y, 0o644)
		}
	}
	hub := BuildHub()
	if err == nil {
		var j []byte
		if j, err = HubJSON(hub); err == nil {
			err = os.WriteFile(filepath.Join(*out, hubDataKey), j, 0o644)
		}
	}
	if err == nil {
		var y []byte
		if y, err = HubConfigMapYAML(hub); err == nil {
			err = os.WriteFile(*hubCM, y, 0o644)
		}
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "dashgen:", err)
		os.Exit(1)
	}
}
